lenguage: node_js
if: branch = master # condition para el build

stages:
  - name: lint
    if: branch = development # condicion para el stage

jobs:
  include:
    - if: branch = staging # condicion solo para el job
      script: npm run some-command
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
  slack:
    rooms:
      - <account>:<token>#development
      - <account>:<token>#general
  email:
    reciepients:
    - xtremoc.log@gmail.com
   # - oscar@arepa.dev
    on_success: always
    on_failure: always
# manda emails a esos mails cuando es exitoso y cuando falla
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-page
  commit_message: 'Deploy del proyecto'
  on:
    branch: master